@startuml doip_server_modules
/'  Copyright (c) 2026 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under the
terms of the Apache License Version 2.0 which is available at
<https://www.apache.org/licenses/LICENSE-2.0>

SPDX-License-Identifier: Apache-2.0 '/

title DoIP Server Components

top to bottom direction
skinparam componentStyle rectangle
skinparam backgroundColor #FAFAFA
skinparam defaultFontSize 12
skinparam ArrowColor #333333
skinparam packageStyle rectangle

package "UDS-to-SOVD Proxy" as uds2sovd_proxy #LightGoldenRodYellow {
    component "app" as app
    component "config.toml" as app_config
}

package "uds2sovd-proxy-lib" as uds2sovd_proxy_lib #LightCyan {
    component "server" as server #Azure {
        component "tcp"
        component "udp"
    }
    component "doip" as doip #Azure {
        component "tcp_dispatcher"
        component "udp_dispatcher"
        component "handlers" as handlers {
            component "diagnostic"
            component "discovery"
        }
    }
    component "config" as config #Azure {
        component "config_provider" as config_provider
    }
}

package "proxy" as proxy #Azure {
    component "stub_proxy"
}

package "translation" as translation #Azure {
    component "uds2sovd_translation"
}

uds2sovd_proxy -[hidden]down-> uds2sovd_proxy_lib
server -[hidden]down-> doip
doip -[hidden]down-> handlers

app --> server: instantiates
app --> app_config: uses
app --> config_provider: gets server_config

tcp --> tcp_dispatcher: forwards\nTCP messages
udp --> udp_dispatcher: forwards\nUDP messages
diagnostic -up-> tcp_dispatcher: registered with
discovery -up-> udp_dispatcher: registered with
diagnostic --> uds2sovd_translation: forwards\ndiagnostic payloads
uds2sovd_translation --> stub_proxy: translates\nand forwards

@enduml
